server:
  port: 8081  # 强制指定端口为8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver


  ai:
    openai:
      api-key: #密钥
      base-url: #路径
#      暂时不用
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/repository/schema-mysql.sql



  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir} # 将上传目录配置为静态资源路径

file:
  upload-dir: ./uploads # 上传目录路径



